### ISSUE TITLE
wrong dependency for test

### ISSUE THREAD

**Issue by puntogil** [proxytoys/proxytoys#2]
Hi
some tests fails, cause
com.thoughtworks.xstream.converters.ConversionException: java.lang.Class cannot be cast to java.lang.ref.WeakReference
com.thoughtworks.xstream:xstream don't provides this functionality
the only xstream library which use  java.lang.ref.WeakReference is org.jvnet.hudson:xstream [1]
Please, correct xstream groupId in master/pom.xml master/proxytoys/pom.xml
thanks in advance
regards

[1] 
https://issues.jenkins-ci.org/browse/JENKINS-4752
https://kenai.com/projects/hudson/sources/xstream/revision/23

**Comment by joehni** [comment]
Sorry, but Jenkins uses a private version of XStream. ProxyToys depends on the original.
