### ISSUE TITLE
initializationError

### ISSUE THREAD

**Issue by puntogil** [proxytoys/proxytoys#3]
Hi
there is a "initializationError" problem in the test suite
java.lang.Exception:
The class com.thoughtworks.proxy.AllTests$StandardSuite is not public
The class com.thoughtworks.proxy.AllTests$CglibSuite is not public
"solved" with rhe following patch
regards

```
--- proxytoys/src/test/java/com/thoughtworks/proxy/AllTests.java	2010-05-13 13:19:38.000000000 +0200
+++ proxytoys/src/test/java/com/thoughtworks/proxy/AllTests.java.test	2015-04-02 11:10:37.157147989 +0200
@@ -68,7 +68,7 @@
             PoolTest.class,
             PrivilegingTest.class
     })
-    static class CglibSuite {
+    public static class CglibSuite {
         public CglibSuite() {
             AbstractProxyTest.PROXY_FACTORY = new CglibProxyFactory();
         }
@@ -89,7 +89,7 @@
             PoolTest.class,
             PrivilegingTest.class
     })
-    static class StandardSuite {
+    public static class StandardSuite {
         public StandardSuite() {
             AbstractProxyTest.PROXY_FACTORY = new StandardProxyFactory();
         }
```

**Comment by joehni** [comment]
The tests are executed fine with Maven and also from within Eclipse.

**Comment by joehni** [comment]
No feedback.

**Comment by puntogil** [comment]
hi
sorry for delay.
Apache Maven 3.2.5 (NON-CANONICAL_2015-04-01T06:42:27_mockbuild; 2015-04-01T08:42:27+02:00)
Maven home: /usr/share/maven
Java version: 1.8.0_51, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.51-4.b16.fc22.i386/jre
Default locale: it_IT, platform encoding: UTF-8
OS name: "linux", version: "4.1.5-200.fc22.i686", arch: "i386", family: "unix"

**Comment by puntogil** [comment]
we use:
cglib 3.1
junit 4.12
xstream 1.4.7 (see https://github.com/proxytoys/proxytoys/issues/2)
mockito 1.9.0

**Comment by joehni** [comment]
OK. However this does not explain, why you want those methods to be public. [Travis](https://travis-ci.org/proxytoys/proxytoys) explicitly demonstrates that all unit tests are executed with the current setup (see configuration of surefire plugin). So we see no reason to change something.

BTW: Unit tests with cglib:cglib-nodep:3.1 will fail on a Java 8 runtime.
